# Written by videoclip on Thu Dec 25 16:31:11 2025.
video_format=mp4
video_bitrate=1M
video_width=-2
video_height=720
video_fps=auto
audio_format=aac
audio_bitrate=128k
video_folder_path=/home/yurareru/Videos
font_size=24
osd_align=7
osd_outline=1.5
clean_filename=yes
preset=faster
litterbox_expire=72h
sub_font=Noto Sans CJK JP
filename_template=%n_%s-%e
video_quality=23
audio_folder_path=/home/yurareru/Music
litterbox=yes
