# preload = $HOME/Pictures/Wallpapers/68174456_p0.png
# wallpaper = ,$HOME/Pictures/Wallpapers/68174456_p0.png
splash = false

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Wallpapers/68174456_p0.png
}
wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/68174456_p0.png
}

